/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Bill.Bill;
import Bill.ManipulateBill;
import Category.Category;
import Category.ManipulateCategory;
import Employee.Employee;
import Patterns.Validate;
import Product.ManipulateProduct;
import Product.Product;
import Table.FillTable;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import static com.lowagie.text.rtf.RtfWriter.paragraph;
import java.io.File;
import java.io.FileOutputStream;
import static java.lang.Integer.parseInt;
import PDF.OpenPdf;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author omars
 */
public class PlaceOrder extends javax.swing.JFrame {
private int grandTotal=0;
private ArrayList<Object> categoryList; 
 private int billId;
 private ArrayList<Object> productList;
 private int productPrice = 0;
 private int productTotal=0;
 private Employee emp=null ;
    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        productText.setEditable(false);
        priceText.setEditable(false);
        totalText.setEditable(false);
               btnBill.setEnabled(false);
        reset();
        JFormattedTextField tf = ((JSpinner.DefaultEditor)qtn.getEditor()).getTextField();
        tf.setEnabled(false);
          productTable.setDefaultEditor(Object.class, null);
    }
     public PlaceOrder(Employee emp) {
        initComponents();
        productText.setEditable(false);
        priceText.setEditable(false);
        totalText.setEditable(false);
               btnBill.setEnabled(false);
        reset();
        JFormattedTextField tf = ((JSpinner.DefaultEditor)qtn.getEditor()).getTextField();
        tf.setEnabled(false);
          productTable.setDefaultEditor(Object.class, null);
          this.emp = emp;
    }
public void reset ()
{
        priceText.setText("");
        productText.setText("");
        qtn.setValue(1);
        btnAdd.setEnabled(false);
 
}
public void validateInput ()
{  String name = nameText.getText();
   String phone = phoneText.getText();
   String email=emailText.getText();
   Validate validate = new Validate ();
   if(!name.equals("")&&!phone.equals("")&&!email.equals("")&&grandTotal>0&&validate.validateEmail(email)&&validate.validatePhoneNumber(phone))
         btnBill.setEnabled(true);
   else
       btnBill.setEnabled(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        productText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        totalText = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        btnBill = new javax.swing.JButton();
        qtn = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        grandLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 30));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\bell.png")); // NOI18N
        jLabel1.setText("Palce Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 185, 44, -1));

        idLabel.setBackground(new java.awt.Color(255, 255, 255));
        idLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("00");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 185, 34, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 274, 56, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 342, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 416, -1, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 305, 208, -1));

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });
        phoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTextKeyReleased(evt);
            }
        });
        getContentPane().add(phoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 379, 208, -1));

        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextKeyReleased(evt);
            }
        });
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 453, 208, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Customer details:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 218, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 88, 73, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 119, 250, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 160, 60, -1));

        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });
        getContentPane().add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 199, 250, -1));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 305, 288, 361));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 39, 57, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 39, 54, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantity:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 120, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));
        getContentPane().add(productText, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 75, 175, -1));
        getContentPane().add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 75, 175, -1));
        getContentPane().add(totalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 145, 175, -1));

        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\clear.png")); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 192, 104, -1));

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\billing2.png")); // NOI18N
        btnAdd.setText("Add to bill");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 192, -1, -1));

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Qtn", "Total"
            }
        ));
        billTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(billTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 240, -1, -1));

        btnBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\billing2.png")); // NOI18N
        btnBill.setText("Generate Bill");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 680, 163, -1));

        qtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtnStateChanged(evt);
            }
        });
        getContentPane().add(qtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 145, 175, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grand Total:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 686, -1, -1));

        grandLabel.setBackground(new java.awt.Color(255, 255, 255));
        grandLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        grandLabel.setForeground(new java.awt.Color(255, 255, 255));
        grandLabel.setText("0000");
        getContentPane().add(grandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 686, 59, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\cross.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1334, 12, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\RestaurantSystem\\Icons\\full-page-background.PNG")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
 
    ManipulateBill mani = new ManipulateBill();
    try {
        billId=parseInt(mani.maxId());
        
        // TODO add your handling code here:
    } catch (SQLException ex) {
        System.out.println(ex.getMessage());
    }
    idLabel.setText(String.valueOf(billId));
    ManipulateCategory manicat = new ManipulateCategory ();
  categoryList=  manicat.retrive();
   Category category =new Category ();
   for(int i=0;i<categoryList.size();i++)
   {
      
       category=(Category)categoryList.get(i);
       jComboBox1.addItem(category.getName());
   }
      int index = jComboBox1.getSelectedIndex();
      FillTable ft=new FillTable ();
      category =(Category)categoryList.get(0);
    try {
        ft.fillTableProductByCategory(productTable,category.getId() );
    } catch (SQLException ex) {
        Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }//GEN-LAST:event_formComponentShown

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
       String name = searchText.getText();
       int index= jComboBox1.getSelectedIndex();
       Category category = (Category)categoryList.get(index);
       ManipulateProduct mani = new ManipulateProduct();
       productList=mani.retrive(name, category.getId());
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        dtm.setRowCount(0);
     for(int i=0;i<productList.size();i++)
     {     
      
         Product product = (Product)productList.get(i);
        
   
    dtm.addRow(new Object[]{product.getName()});
     
     }
    }//GEN-LAST:event_searchTextKeyReleased

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
      int index = productTable.getSelectedRow();
      TableModel tm = productTable.getModel();
      String productName = tm.getValueAt(index, 0).toString();
      ManipulateProduct mani = new ManipulateProduct ();
      Product product = mani.retriveByName(productName);
      productText.setText(product.getName());
      priceText.setText(String.valueOf(product.getPrice()));
      qtn.setValue(1);
      totalText.setText(String.valueOf(product.getPrice()));
      productPrice=product.getPrice();
       productTotal=product.getPrice();
       btnAdd.setEnabled(true);
    }//GEN-LAST:event_productTableMouseClicked

    private void qtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtnStateChanged
    int quantity =(Integer) qtn.getValue();
    if(quantity<=1)
    {
           qtn.setValue(1);
           quantity=1;
    }
    productTotal=productPrice*quantity;
    totalText.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_qtnStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int index = jComboBox1.getSelectedIndex();
      FillTable ft=new FillTable ();
     Category category =(Category)categoryList.get(index);
    try {
        ft.fillTableProductByCategory(productTable,category.getId() );
    } catch (SQLException ex) {
        Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name= productText.getText();
        String price = priceText.getText();
        String qunatity=String.valueOf(qtn.getValue());
        String total = totalText.getText();
        DefaultTableModel dtm = (DefaultTableModel)billTable.getModel();
        dtm.addRow(new Object[]{name,price,qunatity,total});
        grandTotal+=productTotal;
        grandLabel.setText(String.valueOf(grandTotal));
        reset();
        validateInput();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
reset();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
validateInput();        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextKeyReleased

    private void phoneTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextKeyReleased
validateInput();        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextKeyReleased

    private void emailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyReleased
validateInput();        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextKeyReleased

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
String customerName = nameText.getText();
String customerphone=phoneText.getText();
String customerEmail=emailText.getText();
SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yyyy");

  Date date = new Date();
   String todayDate = sdf.format(date);
   String total = String.valueOf(grandTotal);
   // ??????????????????????
   if(emp!=null)
   {
       Bill bill = new Bill(billId,customerName,customerphone,customerEmail,todayDate,parseInt(total),emp.getId());
   }
   int id = 5;
   Bill bill = new Bill(billId,customerName,customerphone,customerEmail,todayDate,parseInt(total),id);
   ManipulateBill mani = new ManipulateBill();
   mani.add(bill);
  String path = "F:\\RestaurantSystem\\Orders\\";
  com.lowagie.text.Document doc = new com.lowagie.text.Document();
  try{
      PdfWriter.getInstance(doc, new FileOutputStream(path+""+billId+".pdf"));
      doc.open();
      Paragraph cafeName = new Paragraph ("                                       PotatoScript\n");
      doc.add(cafeName);
      Paragraph starLine = new Paragraph ("*****************************************************************************\n"); 
      doc.add(starLine);
      doc.add(starLine);
      Paragraph info = new Paragraph("\tBill ID:  "+billId+"\nCustomer Name:  "+customerName+"\nTotal Paid:  "+grandTotal);
doc.add(info);
doc.add(starLine);
doc.add(starLine);

PdfPTable tb1 = new PdfPTable(4);
tb1.addCell("Name");
tb1.addCell("Price");
tb1.addCell("Qtn");
tb1.addCell("Total");
for(int i=0;i<billTable.getRowCount();i++)
{
    String a = billTable.getValueAt(i, 0).toString();
    String b = billTable.getValueAt(i, 1).toString();
    String c = billTable.getValueAt(i, 2).toString();
    String d = billTable.getValueAt(i, 3).toString();
    tb1.addCell(a);
    tb1.addCell(b);
    tb1.addCell(c);
    tb1.addCell(d);
}
doc.add(tb1);
doc.add(starLine);
doc.add(starLine);
Paragraph thankyou = new Paragraph("Thank you, Please visit us again");
doc.add(thankyou);
PDF.OpenPdf.openById(String.valueOf(billId));
  }
  catch(Exception e)
  {
      System.out.println(e.getMessage());
  }
  doc.close();
  this.dispose();
  new PlaceOrder().setVisible(true);
    }//GEN-LAST:event_btnBillActionPerformed

    private void billTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTableMouseClicked
        int index = billTable.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "do you want to remove this product","choose",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            TableModel tm= billTable.getModel();
            String total =tm.getValueAt(index, 3).toString();
            grandTotal-=parseInt(total);
            grandLabel.setText(String.valueOf(grandTotal));
            ((DefaultTableModel)billTable.getModel()).removeRow(index);
            
        }
    }//GEN-LAST:event_billTableMouseClicked

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnClear;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel grandLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTextField priceText;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField productText;
    private javax.swing.JSpinner qtn;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
